[env:esp32s3zero]
platform = espressif32
board = waveshare_esp32_s3_zero
framework = arduino
upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.filesystem = littlefs
board_build.partitions = huge_app.csv
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    bblanchon/ArduinoJson @ 6.21.5
    knolleary/PubSubClient @ 2.8.0
    links2004/WebSockets @ 2.7.3
    lsatan/SmartRC-CC1101-Driver-Lib @ 2.5.7
